import styles from '../../../components/notes_layout.module.css';
import Layout from '../../../components/notes_layout';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Intro_Graphics() {
    const parent = "Computer Graphics"
    const title = 'Introduction';
    /* TOC should be generated by markdown file */
    const tableOfContents = [
        {
          heading: "Introduction",
          chapters: []
        },
        {
          heading: "Drawing Triangles",
          chapters: ["Rasterization", "Sampling Pixelbuffer"]
        }
      ];

    return (
        <>
            <Head>
                <title>{title}</title>
                <link
                    rel="icon"
                    href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🌊</text></svg>" />
            </Head>
            <Layout title={title} tableOfContents={tableOfContents}>
                <div className={styles.leftColumn}>
                </div>
                <div className={styles.rightColumn}>
                    <Link href="/notes/computer-graphics" className={styles.bookLink}>
                        <p className={styles.contentTag}>{parent} / {title}</p>
                    </Link>
                    <h3>{title}</h3>
                    <hr></hr>
                    <p>Normal text</p>
                </div>
            </Layout>
        </>
    );
}